
DATASET:
  DATA: "SA"

PIPELINE:

  # NUM_QUANTILE_BINS: [2,3,5,10,20]
  NUM_QUANTILE_BINS: [5]

  COMBINE_MIDDLE_BINS: False
  PIXEL_TO_MM_SCALE: 0.9375
  IND_LANDMARKS_TO_SHOW: [0,1,2]
  COMPARE_Q_VALUES: True
  COMPARE_INDIVIDUAL_Q: True 
  COMPARE_Q_MODELS: ["PHD-NET", "U-NET"]
  COMPARE_Q_UNCERTAINTY_ERROR_PAIRS: [["E-MHA", "E-MHA Error", "E-MHA Uncertainty"], ["S-MHA", "S-MHA Error", "S-MHA Uncertainty"], ["E-CPV", "E-CPV Error", "E-CPV Uncertainty"]]
  INDIVIDUAL_Q_MODELS: ["U-NET", "PHD-NET"] 
  SHOW_IND_LANDMARKS: False

BOXPLOT:
  ERROR_LIM: 64 
  SAMPLES_AS_DOTS: True
  SHOW_SAMPLE_INFO_MODE: "Average" 


OUTPUT:
  SAVE_FIGURES: False
  SAVE_PREPEND: "8std_10_08_22"

